version: "3.9"

services:
  #########################################
  # LocalStack - AWS simulator
  #########################################
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,dynamodb,sqs,s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

  #########################################
  # Frontend
  #########################################
  frontend:
    build:
      context: ./ffn-material-management
    container_name: react-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4566
    depends_on:
      - localstack

